### ISSUE TITLE
Can't save config

### ISSUE THREAD

**Issue by benvallack** [mayanez/dumang-keyboard-ctrl#11]
I seem to almost be there with this but the config command doesn't seem to change anything. 

This is my config 
```
# This is just a sample config
kb1:
  serial: 05DAFF3438314D4743098923
  keys:
    key_03:
      layer_0: I
      layer_1: Q
kb2:
  serial: 05D6FF383431474843167116 # Replace with your keyboard serial
  keys:
    key_03:
      layer_0: K/LT1
```

I'm not sure what the correct way to designate a layer switch (for next key press) is on the last line. 

In any case the output for the kb1 > key_03 > layer_0 isn't 'I' it is the original 'A'. 

Here is the output from `dumang-config config dumang.yml`:

```
DuMangPacket - CMD:31 raw:[0x0, 0x41, 0x1, 0x3c, 0x1, 0x2c, 0xb, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x23, 0x36, 0x1, 0x8, 0x0, 0xe0, 0x1, 0x8, 0x0, 0xe0, 0x1, 0x8, 0x0, 0xe0, 0x1, 0x8, 0x23, 0x36, 0x1, 0x8, 0x0, 0xe0, 0x1, 0x8, 0xf9, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0xbd, 0x27, 0x0, 0x20, 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, 0x0]
DuMangPacket - CMD:31 raw:[0x0, 0x41, 0x1, 0x3c, 0x1, 0x2c, 0xb, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x23, 0x36, 0x1, 0x8, 0x0, 0xe0, 0x1, 0x8, 0xf9, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0xbd, 0x27, 0x0, 0x20, 0xff, 0xff, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, 0x0, 0x37, 0x55, 0x1, 0x8, 0x32, 0x82, 0x1, 0x8, 0x0, 0xf0, 0x0, 0x61, 0xff, 0xff, 0xff, 0xff]
```
